// Mage Knight Rules Engine v1
// Referee only: never recommend strategy. Results are ERROR / INSUFFICIENT / NO_KNOWN_ERROR.
const RULE_SOURCE='https://www.mageknight.net/wp-content/uploads/Mage-Knight-Board-Game-Ultimate-Edition-Rule-Book-September-2018.pdf';
const rules=[
{id:'CONCENTRATION_MANA',match:/(?:concentration|集中精神).*(?:取得|產生|生成|增加).*(?:mana|魔力)/i,evaluate:()=>({type:'ok',title:'✓ 未發現違規',body:'Concentration 取得 Mana 本身不是規則錯誤。若你還要利用 Concentration 的複合效果去使用另一張牌，必須另外檢查被使用效果的類型、限制與時機。'})},
{id:'CONCENTRATION_TARGET',match:/(?:concentration|集中精神).*(?:法術|spell|單位|unit|神器|artifact)/i,evaluate:()=>({type:'insufficient',title:'⚠️ 資訊不足：需要具體牌名',body:'不能只因出現 Spell、Unit 或 Artifact 就直接判定違規。請提供具體牌名與你要使用的效果，裁判再檢查該效果的類型與限制。'})},
{id:'UNIT_REPEAT',match:/(?:unit|部隊|單位).*(?:再|再次|第二次|兩次|2次|又).*(?:啟動|使用)/i,evaluate:({state})=>state.unitState==='spent'?{type:'error',title:'❌ 違規：Unit 已經是 Spent',body:'目前遊戲狀態顯示該 Unit 已經 Spent；不能再次使用其一般 Unit 能力，除非有明確效果使它重新 Ready。'}:{type:'insufficient',title:'⚠️ 資訊不足：需要 Unit 狀態',body:'請確認該 Unit 目前是 Ready 還是 Spent，以及是否有任何效果使它重新 Ready。'}},
{id:'UNIT_DAMAGE',match:/(?:已使用|用過|spent).*(?:部隊|unit|單位).*(?:格擋|承受|分配).*(?:傷害)/i,evaluate:()=>({type:'insufficient',title:'⚠️ 資訊不足：啟動與傷害分配是不同檢查',body:'不能因 Unit 已使用過，就直接推論它不能參與傷害處理。請提供敵人、傷害值、Unit 能力與目前戰鬥階段。'})},
{id:'DIRECT_FAME',match:/(?:直接拿|直接取得|直接獲得).*(?:fame|聲望|名望)/i,evaluate:()=>({type:'insufficient',title:'⚠️ 資訊不足：需要完整戰鬥狀態',body:'不能僅憑「直接拿 Fame」判定違規。請提供敵人、是否已擊敗敵人、戰鬥階段與 Fame 的來源。'})},
{id:'BLOCK_PHASE',match:/(?:格擋|block).*(?:攻擊|傷害)/i,evaluate:({state})=>state.phase==='Attack'?{type:'error',title:'❌ 可能的階段錯誤',body:'目前狀態是 Attack 階段。若你正在處理敵人的攻擊，必須確認是否已經錯過 Block 階段。'}:state.phase==='Block'?{type:'ok',title:'✓ 階段符合',body:'目前為 Block 階段；下一步應檢查你使用的 Block 效果、敵人攻擊類型與數值。'}:{type:'insufficient',title:'⚠️ 資訊不足：需要戰鬥階段',body:'請將戰鬥階段設定為 Block，或提供完整戰鬥流程。'}}
];
function stateFromUI(){return{round:Number(document.getElementById('round')?.value||1),time:document.getElementById('time')?.value||'Day',unitState:document.getElementById('unitState')?.value||'unknown',phase:document.getElementById('phase')?.value||'unknown'}}
function check(text,state={unitState:'unknown',phase:'unknown'}){const value=(text||'').trim();if(!value)return{type:'insufficient',title:'⚠️ 無法判定：沒有行動敘述',body:'請描述誰使用什麼、做什麼、在什麼階段、針對什麼目標。'};for(const rule of rules)if(rule.match.test(value))return rule.evaluate({text:value,state});return{type:'insufficient',title:'⚠️ 資訊不足：不是「合法」',body:'目前沒有規則足以證明這個行動違規，也沒有足夠資訊證明它合法。請補充卡牌/Unit 名稱、遊戲階段、目標、Mana、相關效果與目前狀態。'}}
if(typeof window!=='undefined'){const action=document.getElementById('action'),result=document.getElementById('result');function escapeHtml(s){return s.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}function render(){const r=check(action.value,stateFromUI());result.className=`result ${r.type}`;result.innerHTML=`<div class="verdict">${escapeHtml(r.title)}</div><div>${escapeHtml(r.body).replaceAll('\n','<br>')}</div><div class="source"><a href="${RULE_SOURCE}" target="_blank" rel="noopener">規則來源：Mage Knight Ultimate Edition Rule Book</a></div>`}document.getElementById('checkBtn')?.addEventListener('click',render);document.getElementById('clearBtn')?.addEventListener('click',()=>{action.value='';result.className='result empty';result.textContent='等待判定……';action.focus()});document.querySelectorAll('[data-example]').forEach(btn=>btn.addEventListener('click',()=>{action.value=btn.dataset.example;render()}));action?.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')render()})}
