// Mage Knight Rules Engine v3.3
// Referee only: never recommend strategy. Results: violation / insufficient / ok.
const RULE_SOURCE='https://www.mageknight.net/wp-content/uploads/Mage-Knight-Board-Game-Ultimate-Edition-Rule-Book-September-2018.pdf';
function normalizeActionV2(text){const value=String(text||'').trim(),out={raw:value,action:'unknown',entities:{},signals:[],confidence:0},has=r=>r.test(value);if(!value)return out;
const explicitAttackPhase=has(/(?:attack|攻擊)\s*(?:phase|階段)/i),explicitBlockPhase=has(/(?:block|格擋)\s*(?:phase|階段)/i);
if(has(/(?:使用|啟動|activate|use)[\s\S]*(?:unit|部隊|單位)|(?:unit|部隊|單位)[\s\S]*(?:使用|啟動)/i)||has(/(?:再次|再|第二次|又|again|second time)[\s\S]*(?:使用|啟動|use|activate)[\s\S]*(?:unit|部隊|單位)/i)||has(/(?:use|activate)\s+(?:the\s+)?(?:spent\s+)?unit(?:\s+again)?/i)){out.action='use_unit';out.confidence=.95}
else if(has(/(?:concentration|集中精神)[\s\S]*(?:mana|魔力)/i)){out.action='concentration_mana';out.confidence=.95}
else if(explicitAttackPhase&&has(/(?:block|格擋)/i)||has(/(?:格擋|block)[\s\S]*(?:攻擊|傷害)/i)||explicitBlockPhase&&has(/(?:block|格擋)/i)){out.action='block';out.confidence=.95}
else if(has(/(?:攻擊|attack)[\s\S]*(?:敵人|enemy|orc|敵軍)|(?:攻擊|attack)\s*$/i)){out.action='attack';out.confidence=.8}
else if(has(/(?:移動|move)(?:到|至|往|進入|into|to)?[\s\S]*(?:森林|平原|沙漠|沼澤|forest|plains|desert|swamp)/i)){out.action='move';out.confidence=.85}
if(has(/(?:spent|已使用|用過|已用過)/i))out.entities.unitState='spent';else if(has(/(?:ready|就緒|可用)/i))out.entities.unitState='ready';
if(has(/(?:night|晚上|夜間)/i))out.entities.time='Night';else if(has(/(?:day|白天)/i))out.entities.time='Day';if(has(/(?:forest|森林)/i))out.entities.terrain='forest';
if(has(/(?:再|再次|第二次|兩次|2次|又|again|second time)/i))out.signals.push('repeat_use');if(has(/(?:可以嗎|能不能|是否合法)/i))out.signals.push('question');if(has(/(?:一定|確定|合法)/i))out.signals.push('legality_claim');
const attackMatch=value.match(/(?:用|with|using)?\s*(\d+)\s*(?:點|點的|points?|attack|攻擊力)/i);if(attackMatch)out.entities.attack=Number(attackMatch[1]);
const defenseMatch=value.match(/(?:有|防禦|defense|defence)\s*(\d+)\s*(?:點|points?)?/i);if(defenseMatch)out.entities.enemyDefense=Number(defenseMatch[1]);
const enemyMatch=value.match(/(?:攻擊|attack)(?:[^\n]{0,20})(?:敵人|enemy|orc|Goblin|Dragon|骷髏)/i);if(enemyMatch)out.entities.enemy=enemyMatch[0].replace(/.*(?:敵人|enemy)\s*/i,'').trim()||'target';
if(out.action==='block'){if(explicitAttackPhase)out.entities.phase='Attack';else if(explicitBlockPhase)out.entities.phase='Block';}else if(out.action==='attack'&&explicitAttackPhase)out.entities.phase='Attack';return out}
function check(text,uiState={unitState:'unknown',phase:'unknown'}){const n=normalizeActionV2(text);if(!n.raw)return{type:'insufficient',title:'⚠️ 無法判定：沒有行動敘述',body:'請描述誰使用什麼、做什麼、在什麼階段、針對什麼目標。',normalized:n};
if(n.action==='use_unit'){if(n.signals.includes('repeat_use')){if(n.entities.unitState==='spent'||uiState.unitState==='spent')return{type:'violation',title:'❌ 違規：Unit 已經是 Spent',body:'此行動被標準化為「再次使用 Unit」，而目前狀態為 Spent。除非有明確 Ready 效果，否則不能再次使用。',ruleId:'UNIT_SPENT_REPEAT',normalized:n};return{type:'insufficient',title:'⚠️ 資訊不足：需要 Unit 狀態',body:'已辨識為再次使用 Unit，但尚缺 Ready/Spent 狀態，不能直接判定合法或違規。',ruleId:'UNIT_STATE_REQUIRED',normalized:n}}const unitState=n.entities.unitState&&n.entities.unitState!=='unknown'?n.entities.unitState:uiState.unitState||'unknown';if(unitState==='spent')return{type:'violation',title:'❌ 違規：Unit 已經是 Spent',body:'該 Unit 目前為 Spent；目前沒有提供可使其 Ready 的效果，因此不能再次啟動。',ruleId:'UNIT_SPENT_REPEAT',normalized:n};if(unitState==='ready')return{type:'ok',title:'✓ 可以使用 Unit',body:'已確認 Unit 狀態為 Ready；目前沒有發現 Unit 狀態上的違規。執行後該 Unit 將進入 Spent。',ruleId:'UNIT_USE_VALID',normalized:n};return{type:'insufficient',title:'⚠️ 資訊不足：需要 Unit 狀態',body:'已辨識為使用 Unit，但尚缺 Ready/Spent 狀態，不能直接判定合法或違規。',ruleId:'UNIT_STATE_REQUIRED',normalized:n}}
if(n.action==='concentration_mana')return{type:'ok',title:'✓ 未發現違規',body:'已辨識為 Concentration 取得 Mana；此描述本身不足以構成違規。',ruleId:'CONCENTRATION_MANA',normalized:n};
if(n.action==='block'){const phase=uiState.phase!=='unknown'?uiState.phase:n.entities.phase;if(phase==='Attack')return{type:'violation',title:'❌ 可能的階段錯誤',body:'目前遊戲狀態為 Attack，不能在此階段執行 Block。',ruleId:'BLOCK_PHASE',normalized:n};if(phase==='Block')return{type:'ok',title:'✓ 階段符合',body:'目前遊戲狀態為 Block；仍需檢查具體效果與攻擊數值。',ruleId:'BLOCK_PHASE_VALID',normalized:n};return{type:'insufficient',title:'⚠️ 資訊不足：需要戰鬥階段',body:'已辨識為 Block，但目前沒有可靠的戰鬥階段資料。',ruleId:'BLOCK_PHASE_REQUIRED',normalized:n}}
if(n.action==='attack'){const phase=uiState.phase||'unknown',enemy=uiState.enemy||n.entities.enemy,attack=uiState.attack??n.entities.attack,defense=uiState.enemyDefense??n.entities.enemyDefense;if(phase!=='Attack')return{type:'insufficient',title:'⚠️ 資訊不足：需要完整戰鬥狀態',body:'已辨識為 Attack，但尚缺正確的 Attack 階段。',ruleId:'ATTACK_STATE_REQUIRED',normalized:n};if(!enemy||attack===undefined||defense===undefined)return{type:'insufficient',title:'⚠️ 資訊不足：需要完整戰鬥狀態',body:'需要敵人、攻擊值與敵人防禦值，才能進行 Combat 結算。',ruleId:'ATTACK_STATE_REQUIRED',normalized:n};const damage=Math.max(0,Number(attack)-Number(defense));return{type:'ok',title:'✓ 攻擊宣告可進行結算',body:`Target: ${enemy}<br>Attack: ${attack}<br>Enemy Defense: ${defense}<br>Damage: ${damage}`,ruleId:'COMBAT_ATTACK_RESOLUTION',normalized:{...n,entities:{...n.entities,enemy,attack,enemyDefense:defense,damage}}}}
if(n.action==='move')return{type:'insufficient',title:'⚠️ 資訊不足：需要移動狀態',body:'已辨識為 Movement，但尚缺角色移動力、目前位置、目的地地形成本與相關效果，不能直接判定合法或違規。',ruleId:'MOVEMENT_STATE_REQUIRED'};return{type:'insufficient',title:'⚠️ 資訊不足：無法完成規則判定',body:'目前無法將行動可靠地對應到可判定的規則。請補充行動、目標與遊戲狀態。',ruleId:'UNKNOWN_ACTION',normalized:n}}
function stateFromUI(){return{round:Number(document.getElementById('round')?.value||1),time:document.getElementById('time')?.value||'Day',unitState:document.getElementById('unitState')?.value||'unknown',phase:document.getElementById('phase')?.value||'unknown',enemy:document.getElementById('enemy')?.value||'',attack:document.getElementById('attack')?.value===''?undefined:Number(document.getElementById('attack')?.value),enemyDefense:document.getElementById('enemyDefense')?.value===''?undefined:Number(document.getElementById('enemyDefense')?.value)}}
if(typeof window!=='undefined'){const action=document.getElementById('action'),result=document.getElementById('result');function escapeHtml(s){return String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}function render(){const r=check(action.value,stateFromUI());result.className=`result ${r.type}`;result.innerHTML=`<div class="verdict">${escapeHtml(r.title)}</div><div>${r.body||''}</div><div class="rule-id">Rule: ${escapeHtml(r.ruleId||'—')}</div><div class="source"><a href="${RULE_SOURCE}" target="_blank" rel="noopener">規則來源：Mage Knight Ultimate Edition Rule Book</a></div>`}document.getElementById('checkBtn')?.addEventListener('click',render);document.getElementById('clearBtn')?.addEventListener('click',()=>{action.value='';result.className='result empty';result.textContent='等待判定……';action.focus()});document.querySelectorAll('[data-example]').forEach(btn=>btn.addEventListener('click',()=>{action.value=btn.dataset.example;render()}));action?.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key==='Enter')render()})}if(typeof module!=='undefined')module.exports={normalizeActionV2,check};